[package]
name = "warped-sampling"
version = "0.1.0"
authors = ["Jasper-Bekkers <bekkers@gmail.com>"]
edition = "2018"

[dev-dependencies]
halton = "0.1.0"
minifb = "0.11.2"
imageproc = "0.18"
image = "0.21.1"
num = "0.2.0"